module.exports = {
  "extends": "airbnb-base",
  "plugins": ["prettier"],
  "rules": {
    "prettier/prettier": [
      "warn",
      {
        endOfLine: "auto",
      },
    ],
    "linebreak-style": ["off", "windows"],
    "import/no-extraneous-dependencies": ["off"],
    "import/prefer-default-export": ["off"],
    "import/no-unresolved": ["off"],
    "react/prop-types": ["off"],
    "no-param-reassign": ["off"],
    "no-trailing-spaces": ["off"],
    "comma-dangle": ["off"],
    indent: ["off"],
    "function-paren-newline": ["off"],
    "no-multi-spaces": ["off"],
    "jsx-quotes": ["off"],
    "object-curly-newline": ["off"],
    "react/jsx-curly-newline": "off",
    "implicit-arrow-linebreak": ["off"],
    "operator-linebreak": ["off"],
    "arrow-body-style": ["off"],
    "consistent-return": ["off"],
    "react/jsx-props-no-spreading": "off",
    "react/jsx-filename-extension": [
      2,
      { extensions: [".js", ".jsx", ".ts", ".tsx"] },
    ],
    "import/extensions": [
      "error",
      "ignorePackages",
      {
        js: "never",
        jsx: "never",
        ts: "never",
        tsx: "never",
      },
    ],
    "quotes": [2, "single", { avoidEscape: true }],
    "max-len": ["error", { code: 800 }],
    "no-shadow": "off",
    "@typescript-eslint/no-shadow": ["error"],
    "react/require-default-props": "off",
  },
  settings: {
    "import/resolver": {
      typescript: {},
    },
  },
};
